package com.mitchej123.glsm;

public interface GLStateManagerService {
    default int getPriority() {
        return 0;
    }
    int glGetInteger(int pname);
    String glGetString(int pname);
    int glGenFramebuffers();
    void glDeleteFramebuffers(int framebuffer);
    void glBindFramebuffer(int target, int framebuffer);
    int glCheckFramebufferStatus(int target);
    void glFramebufferTexture2D(int target, int attachment, int textarget, int texture, int level);
    int glCreateShader(int type);
    void glCompileShader(int shader);
    int glGetShaderi(int shader, int pname);
    String glGetShaderInfoLog(int shader, int maxLength);
    void glDeleteShader(int shader);
    int glCreateProgram();
    void glAttachShader(int program, int shader);
    void glLinkProgram(int program);
    int glGetProgrami(int program, int pname);
    void glUseProgram(int program);
    void glDeleteProgram(int program);
    int glGetUniformLocation(int program, CharSequence name);
    void glUniform1i(int location, int value);
    int glGetAttribLocation(int program, CharSequence name);
    void glBindAttribLocation(int program, int index, CharSequence name);
    int glGenVertexArrays();
    void glBindVertexArray(int array);
    void glDeleteVertexArrays(int array);
    int glGenBuffers();
    void glBindBuffer(int target, int buffer);
    void glDeleteBuffers(int buffer);
    int glGenTextures();
    void glGenTextures(int[] textures);
    void glDeleteTextures(int texture);
    void glDeleteTextures(int[] textures);
    void glActiveTexture(int texture);
    int glGetTexLevelParameteri(int target, int level, int pname);
    int glGetTexLevelParameter(int target, int level, int pname);
    void glCopyTexSubImage2D(int target, int level, int xoffset, int yoffset, int x, int y, int width, int height);
    void glPixelStorei(int pname, int param);
    void enableCullFace();
    void disableCullFace();
    void enableBlend();
    void disableBlend();
    void glBlendFuncSeparate(int srcRGB, int dstRGB, int srcAlpha, int dstAlpha);
    void enableDepthTest();
    void disableDepthTest();
    void glDepthFunc(int func);
    void glDepthMask(boolean flag);
    void glViewport(int x, int y, int width, int height);
    void glColorMask(boolean red, boolean green, boolean blue, boolean alpha);
    void glClearColor(float red, float green, float blue, float alpha);
    void glClear(int mask);
    void clear(int mask, boolean checkError);
    void bindTexture(int texture);
    int getActiveTexture();
    int getActiveTextureAccessor();
    int getBoundTexture(int internalUnit);
    int getActiveBoundTexture();
    int getViewportWidth();
    int getViewportHeight();
    boolean getDepthStateMask();
    boolean isBlendEnabled();
    void setBoundTexture(int unit, int texture);
    int getTextureBinding(int unit);
}
